baseurl = "http://www.foxypossibilities.com/"
languageCode = "en-us"
title = "Foxy Possibilities"

author = "admin"
theme = "hugo-bootstrap-premium"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  search_engine = true
  google_analytics_id = "XX-XXXXXXXX-X"
  twitter_username = "username"
  disqus_shortname = "sitename"
  paginate = true
