baseurl : "http://www.foxypossibilities.com"
title   : "Foxy Possibilities"

languageCode   : "en-US"
metaDataFormat : "yaml"

theme : "hugo-foxypossibilities-theme"

menu:
  main:
    - Name       : "Home"
      Pre        : "<span class='fi-home'></i>"
      Identifier : "home"
      URL        : "/"
      Weight     : 0

    - Name       : "Tech"
      Identifier : "tech"
      URL        : "/tech"
      Weight     : 10

    - Name       : "Makeup"
      Identifier : "makeup"
      URL        : "/makeup"
      Weight     : 20

    - Name       : "Reviews"
      Parent     : "makeup"
      Identifier : "makeup-reviews"
      URL        : "/makeup/reviews"
      Weight     : 21

    - Name       : "Tutorials"
      Parent     : "makeup"
      Identifier : "makeup-tutorials"
      URL        : "/makeup/tutorials"
      Weight     : 22

    - Name       : "Body Paint"
      Parent     : "makeup"
      Identifier : "makeup-body-paint"
      URL        : "/makeup/body-paint"
      Weight     : 23

    - Name       : "Fashion"
      Identifier : "fashion"
      URL        : "/fashion"
      Weight     : 30

    - Name       : "Hair"
      Parent     : "fashion"
      Identifier : "fashion-hair"
      URL        : "/fashion/hair"
      Weight     : 31

    - Name       : "Masks"
      Parent     : "fashion"
      Identifier : "fashion-masks"
      URL        : "/fashion/masks"
      Weight     : 32

    - Name       : "Jewelry"
      Parent     : "fashion"
      Identifier : "fashion-jewelry"
      URL        : "/fashion/jewelry"
      Weight     : 33

    - Name       : "Costumes"
      Parent     : "fashion"
      Identifier : "fashion-costumes"
      URL        : "/fashion/costumes"
      Weight     : 34

    - Name       : "About"
      Identifier : "about"
      URL        : "/about"
      Weight     : 40
